### ISSUE TITLE
Hosted Example Req

### ISSUE THREAD

**Issue by shiv248** [StopNGo/react-proto-lite#1]
Do you have any example of the app hosted? possibly could be done on Vercel.

**Comment by StopNGo** [comment]
At the moment React Proto Lite does not contain any complete demo application, it is just a template for quick start. There is a complete demo application in the [React Proto](https://github.com/StopNGo/react-proto) and you can check it [here](https://react-proto.onrender.com/).

Do you think this depository needs a full demo? Because now there is just a Hello World page in this project. 

Thanks.

**Comment by shiv248** [comment]
hmm i guess if you add more stuff to the UI for the minified version, it could be useful I was under the impression it would be similar to the react proto.
